// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/get-books': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/get-books').default>>>>
    }
    '/api/get-demo-topics': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/get-demo-topics').default>>>>
    }
    '/api/get-topic': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/get-topic').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}