allowBuilds:
  '@parcel/watcher@2.5.6': true
  'core-js@3.49.0': false
  'esbuild@0.25.12 || 0.27.7 || 0.28.2': true
  'sharp@0.34.5': true
  'vue-demi@0.14.10': true
overrides:
  nitropack: 2.13.0
  ipx>sharp: 0.34.5
