/**
 * Image Shortcode Registry
 * 
 * All image shortcodes are now loaded dynamically from the JSON file generated by /api/image-list.
 * Shortcodes are extracted from lesson chapters and stored in server/data/image-shortcodes.json.
 * Used by the AI Teacher to include images in responses using shortcodes like [image:biology_cell_structure]
 * 
 * Supports both single images (path) and multi-image figures (paths array)
 */

export interface ImageMetadata {
  path?: string;           // Single image URL (for single-image figures)
  paths?: string[];        // Multiple image URLs (for multi-image figures like Figure 1.1 with a,b,c,d)
  alt: string;             // Combined alt text
  alts?: string[];         // Individual alt texts for each sub-image
  category: 'biology' | 'physics' | 'chemistry' | 'mathematics' | 'general';
}

// Cache for dynamic shortcodes loaded from JSON file
let dynamicShortcodesCache: Record<string, ImageMetadata> = {};
let cacheLoadPromise: Promise<void> | null = null;

/**
 * Pre-load all dynamic shortcodes from API (call this on app init or component mount)
 */
export async function loadDynamicShortcodes(): Promise<void> {
  // Only load once
  if (cacheLoadPromise) {
    return cacheLoadPromise;
  }

  cacheLoadPromise = (async () => {
    try {
      // Load all shortcodes from the JSON file via API
      const response = await $fetch<{
        success: boolean;
        images?: Array<{
          shortcode: string;
          path?: string;
          paths?: string[];
          alt: string;
          alts?: string[];
          category: string;
          description?: string;
        }>;
        error?: string;
      }>('/api/image-list?limit=1000'); // Get all shortcodes

      if (response.success && response.images) {
        // Convert to cache format - supports both single and multi-image figures
        for (const image of response.images) {
          const metadata: ImageMetadata = {
            alt: image.alt,
            category: image.category as ImageMetadata['category']
          };
          
          // Handle multi-image figures (paths array)
          if (image.paths && image.paths.length > 0) {
            metadata.paths = image.paths;
            metadata.alts = image.alts;
          } else {
            // Single image figure
            metadata.path = image.path;
          }
          
          dynamicShortcodesCache[image.shortcode] = metadata;
        }
        console.log(`[imageShortcodes] Loaded ${Object.keys(dynamicShortcodesCache).length} dynamic shortcodes`);
      }
    } catch (error) {
      console.warn('[imageShortcodes] Failed to load dynamic shortcodes:', error);
      // Silently fail - direct paths will still work as fallback
    }
  })();

  return cacheLoadPromise;
}

/**
 * Get image metadata from shortcode name
 * @param shortcodeName - The shortcode name (e.g., 'biology_cell_structure_diagram') or direct image path/URL
 * @returns ImageMetadata or null if not found
 */
export const getImageFromShortcode = (shortcodeName: string): ImageMetadata | null => {
  const trimmed = shortcodeName.trim();
  
  // Check cache for dynamic shortcodes (loaded from JSON file)
  if (dynamicShortcodesCache[trimmed]) {
    return dynamicShortcodesCache[trimmed];
  }
  
  // If not found, check if it's a direct path/URL (from chapter images or tool)
  if (
    trimmed.startsWith('http://') || 
    trimmed.startsWith('https://') || 
    trimmed.startsWith('/') ||
    trimmed.match(/\.(jpg|jpeg|png|webp|gif|svg)$/i)
  ) {
    return {
      path: trimmed,
      alt: 'Educational diagram from lesson content',
      category: 'general'
    };
  }
  
  return null;
};

/**
 * Get all available shortcode names (from dynamic cache)
 * @returns Array of shortcode names
 */
export const getAvailableShortcodes = (): string[] => {
  return Object.keys(dynamicShortcodesCache);
};

/**
 * Get shortcodes filtered by category (from dynamic cache)
 * @param category - The category to filter by
 * @returns Array of shortcode names in that category
 */
export const getShortcodesByCategory = (category: ImageMetadata['category']): string[] => {
  return Object.entries(dynamicShortcodesCache)
    .filter(([_, metadata]) => metadata.category === category)
    .map(([shortcode]) => shortcode);
};

/**
 * Replace all image shortcodes in text with image HTML
 * @param text - Text containing shortcodes like [image:biology_cell_structure]
 * @returns Text with shortcodes replaced by HTML img tags
 * Supports both single images and multi-image figures (renders all images in a grid)
 */
export const replaceImageShortcodes = (text: string): string => {
  if (!text) return text;

  // Pattern: [image:shortcode_name]
  const imagePattern = /\[image:([^\]]+)\]/g;

  return text.replace(imagePattern, (match, shortcodeName) => {
    const imageMeta = getImageFromShortcode(shortcodeName.trim());

    if (!imageMeta) {
      // If image not found, return placeholder text in development, original shortcode in production
      if (import.meta.dev) {
        return `<span class="text-gray-400 italic text-sm">[Image not found: ${shortcodeName.trim()}]</span>`;
      }
      return match; // Return original shortcode if not found
    }

    // Check if this is a multi-image figure
    if (imageMeta.paths && imageMeta.paths.length > 0) {
      // Render multiple images in a responsive grid
      const imageGrid = imageMeta.paths.map((imgPath, idx) => {
        const altText = imageMeta.alts?.[idx] || imageMeta.alt;
        return `<div class="flex flex-col items-center">
          <img 
            src="${imgPath}" 
            alt="${altText}" 
            class="max-w-full h-auto rounded-lg shadow-md border border-gray-200"
            loading="lazy"
            onerror="this.parentElement.style.display='none';"
          />
          <span class="text-xs text-gray-500 mt-1">${altText}</span>
        </div>`;
      }).join('');
      
      return `<div class="my-4">
        <div class="grid grid-cols-2 md:grid-cols-${Math.min(imageMeta.paths.length, 4)} gap-3">
          ${imageGrid}
        </div>
        <p class="text-center text-sm text-gray-600 mt-2">${imageMeta.alt}</p>
      </div>`;
    }

    // Single image - return image HTML with proper styling and accessibility
    return `<div class="my-4 flex justify-center">
      <img 
        src="${imageMeta.path}" 
        alt="${imageMeta.alt}" 
        class="max-w-full h-auto rounded-lg shadow-md border border-gray-200"
        loading="lazy"
        onerror="this.style.display='none'; this.nextElementSibling?.style.display='block';"
      />
      <span class="hidden text-gray-400 italic text-sm">Image not available: ${imageMeta.alt}</span>
    </div>`;
  });
};

